name: Publish

on:
  workflow_dispatch:
  push:
    branches: ['master', 'develop']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        context:
          - php7.3/apache
          - php7.3/fpm
          - php7.3/fpm-alpine
          - php7.4/apache
          - php7.4/fpm
          - php7.4/fpm-alpine
          - php8.0/apache
          - php8.0/fpm
          - php8.0/fpm-alpine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Prepares
        id: prepares
        run: |
          slash='/'
          context=${{ matrix.context }}
          version=$(echo ${context//$slash/-})
          tag=${{ github.repository }}:$version
          echo $tag
          echo "::set-output name=tag::$tag"

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.context }}
          tags: ${{ steps.prepares.outputs.tag }}
          push: ${{ github.ref_name == 'master' }}
